INSERT INTO Businesses (name, description, contactInfo)
VALUES ('Soccer Starz', 'Elite soccer training and field rentals for all ages. Improve skills or host games on top-tier turf!', 'soccerstarz@gmail.com'),
		('Amazing Athletics', 'Track rentals, training plans, personalized coaching, equiptment & more!', 'amazingathletics@gmail.com'),
        ('Supreme Swimmers', 'Lane rentals, coaching services, lessons & more!', 'supremeswimmers@gmail.com'),
        ('Limerick Golf Club', 'Improve your game with top-quality golf rentals & expert training.', 'limerickgolfclub@gmail.com'),
        ('Limerick Hurling', 'Train like a pro or rent top-quality gear with our Gaelic football training and rental service!', 'gaelicfbgroup@gmail.com'),
        ('Cycle Craft', 'Expert cycling training & top rentals for all levels—ride stronger, faster, and with confidence!', 'cyclecraft@gmail.com'),
        ('Boxing Business', 'Train like a pro! Rent top-quality boxing gear or book expert training sessions at our gym.', 'boxingbusiness@gmail.com'),
        ('All Star Gymnastics', 'Gymnastics training and rentals for all ages.', 'allstargymnastics@gmail.com'),
        ('Basketball Madness', 'Elite basketball training and court rentals. Improve your game with top-tier facilities!', 'basketballmadness@gmail.com'),
        ('Raging Rugby', 'Rugby training & gear rentals for all levels. Improve skills, rent top equipment, and play harder!', 'ragingrugby@gmail.com');

INSERT INTO Users (firstName, lastName, username, password) VALUES
	('Ethan', 'Cole', 'ecole12', 'ethanpass1'),
    ('Sophia', 'Ramirez', 'sophiaR8', 'sophiapass'),
    ('Liam', 'Patel', 'liam_p', 'liampass12'),
    ('Ava', 'Thompson', 'avaT9', 'avathopass'),
    ('Noah', 'Sullivan', 'noahsully', 'noahspass1'),
    ('Isabella', 'Chan', 'izzychan01', 'isabella12'),
    ('Jacob', 'Foster', 'jfosty45', 'jacobpass1'),
    ('Maya', 'Bennett', 'mayarunz', 'mayapass12'),
    ('Caleb', 'Wright', 'cwright62', 'calebpass1'),
    ('Olivia', 'Sanders', 'livsandy3', 'oliviapass');
    
INSERT INTO Services (serviceName, description, businessID) VALUES
	('Lessons', 'Soccer lessons for groups & individuals.', 1),
    ('Camps', 'Soccer camps available during the off season.', 1),
    ('Equiptment Needs', 'Purchase required soccer equipment.', 1),
    ('Facility Rentals', 'Rent facilities for 2 hours at a time.', 1),
    ('Training Sessions', '2 hr group training sessions.', 2),
    ('Coaching', 'Personalized coaching plans and meetings.', 2),
    ('Equipment Needs', 'Purchase proper equipment for athletics.', 2),
    ('Lane Rentals', 'Rent lanes to train for swimming.', 3),
    ('Coaching', 'Personalized coaching plans and meetings.', 3),
    ('Lessons', 'Swimming lessons for groups & individuals.', 3),
    ('Safety Training', 'Get CPR certified or become a lifeguard.', 3),
    ('Club Passes', 'Gain access to our exclusive golf club.', 4),
    ('Rentals', 'Rent clubs, balls, and golf carts for the day.', 4),
    ('Coaching', 'Personalized coaching plans and meetings.', 5),
    ('Equipment', 'Purchase the equipment you need to play hurling.', 5),
    ('Apparel', 'Purchase team apparel needed for the season.', 5),
    ('Rentals', 'Rent bikes to use any day of the week.', 6),
    ('Leisure', 'Join our bike tours & classes to stay active in a fun envirenment!', 6),
    ('Training', 'Get expert advice to curate training plans and sessions for you to attend.', 6),
    ('Repair', 'All your bike repair needs offered by our business.', 6),
    ('Training', '2 hr group training sessions.', 7),
    ('Membership', 'Gain access to our gym\'s facilities to train.', 7),
    ('Rentals', 'Rent boxing equipment for the day here.', 7),
    ('Classes', 'Basic boxing classes and self defense courses for beginners.', 7),
    ('Coaching', 'Personalized coaching plans and meetings.', 8),
    ('Team Sign-Up', 'Sign up for our gym\'s competitive teams.', 8),
    ('Sessions', 'Come use our facilities for various time sessions.', 8),
    ('Events', 'Host your birthday party or have a playdate in our trampoline gym.', 8),
    ('Coaching', 'Personalized coaching plans and meetings.', 9),
    ('Training', '2 hr group training sessions.', 9),
    ('Facility Rentals', 'Rent facilities for 2 hours at a time.', 9),
    ('Apparel', 'Purchase team apparel needed for the season.', 9),
    ('Coaching', 'Personalized coaching plans and meetings.', 10),
    ('Training', '2 hr group training sessions.', 10),
    ('Certifications', 'Get certified to be a rugby coach or referee.', 10),
    ('Apparel', 'Purchase team apparel needed for the season.', 10);
    
INSERT INTO Subservices (subserviceName, description, cost, serviceID) VALUES
	('One-on-One', 'Personalized training sessions tailored to your individual needs and goals.', 50, 1),
    ('Group', 'Learn and improve your skills in a fun and interactive group setting.', 25, 1),
    ('Summer', 'Attend a 2 month soccer camp to compete & play with friends!', 100, 2),
    ('Winter', 'Attend a 2 month soccer camp to compete & play with friends!', 100, 2),
    ('Cleats', 'Purchase cleats in your desired size.', 50, 3),
    ('Shin Guards', 'Purchase shin guards in your desired size.', 25, 3),
    ('Full Field', '2 hr rental of a full soccer field.', 500, 4),
    ('Half Field', '2 hr rental of half a soccer field.', 250, 4),
    ('Sprinter Session', '2 hr workout session with a coach.', 150, 5),
    ('Distance Session', '2 hr workout session with a coach.', 150, 5),
    ('Jumper Session', '2 hr workout session with a coach.', 150, 5),
    ('Thrower Session', '2 hr workout session with a coach.', 150, 5),
    ('Season Training Plan', 'Detailed training plan formulated for your specific goals.', 300, 6),
    ('Seasonal Coach', 'Weekly practice session for 3 months with a coach.', 300, 6),
    ('Jogging Shoes', 'Purchase shoes designed for daily runs in your size.', 150, 7),
    ('Distance Racing Shoes', 'Purchase shoes designed for distance races in your size.', 180, 7),
    ('Sprinting Racing Shoes', 'Purchase shoes designed for sprinting races in your size.', 180, 7),
    ('Jumping Shoes', 'Purchase shoes designed for jumping events in your size.', 180, 7),
    ('Throwing Shoes', 'Purchase shoes designed for throwing events in your size.', 180, 7),
    ('2 hr Lane Rental', 'Rent one lane in a pool for 2 hours.', 50, 8),
    ('4 hr Lane Rental', 'Rent one lane in a pool for 4 hours.', 50, 8),
    ('Season Training Plan', 'Detailed training plan formulated for your specific goals.', 300, 9),
    ('Seasonal Coach', 'Weekly practice session for 3 months with a coach.', 300, 9),
    ('One-on-One', '2 hr individual swimming lesson with a trainer.', 50, 10),
    ('Group', '2 hr group swimming lesson with a trainer.', 25, 10),
    ('CPR Certification', 'Get CPR certified in a one day safety training class.', 50, 11),
    ('Lifeguard Certification', 'Become a lifeguard in our week long training program.', 150, 11),
    ('1 Yr Membership', 'Gain access to our golf club facilities for 1 year.', 1000, 12),
    ('6 Month Membership', 'Gain access to our golf club facilities for 6 months.', 600, 12),
    ('1 Day Pass', 'Acces our golf club facilities for one day.', 50, 12),
    ('Club Rental', 'Rent a set of golf clubs for the day.', 30, 13),
    ('Ball Rentals', 'Rent a basket of 15 golf balls for the day.', 15, 13),
    ('Cart Rental', 'Rent a golf cart for the day.', 200, 13),
    ('Season Training Plan', 'Detailed training plan formulated for your specific goals.', 300, 14),
    ('Seasonal Coach', 'Weekly practice session for 3 months with a coach.', 300, 14),
    ('Helmet', 'Buy a helmet for hurling.', 25, 15),
    ('Hurley', 'Buy a hurley for hurling.', 25, 15),
    ('Uniform', 'Purchase your hurling team\'s uniform.', 30, 16),
    ('Shorts', 'Purchase shorts for your uniform.', 20, 16),
    ('6 hr Bike Rental', 'Rent a bike for 6 hours.', 25, 17),
    ('1 Day Bike Rental', 'Rent a bike for a day.', 50, 17),
    ('Limerick City Bike Tour', 'Enjoy a 4 hour group tour of Limerick City with a guide.', 100, 18),
    ('Spin Class', 'Work out in a 2 hr class w/music and an instructor.', 50, 18),
    ('Climber Session', '2 hr workout session with a coach.', 150, 19),
    ('Sprinter Session', '2 hr workout session with a coach.', 150, 19),
    ('Damage Assesment & Appraisal', 'Apppraisal service to help assess your bike\'s damage', 25, 6),
    ('Full Bike Repair', 'Replacement parts & repair service completed by an expert.', 150, 20),
    ('Replacement Parts', 'Purchase parts for your bike to replace yourself.', 50, 20),
    ('Speed & Agility Session', '2 hr workout session with a coach.', 150, 21),
    ('Skills Session', '2 hr workout session with a coach.', 150, 21),
    ('Lifting Session', '2 hr workout session with a coach.', 150, 21),
    ('1 Month Membership', 'Access our boxing gym & workout facilities for 1 month.', 50, 22),
    ('3 Month Membership', 'Access our boxing gym & workout facilities for 3 months.', 130, 22),
    ('6 Month Membership', 'Access our boxing gym & workout facilities for 6 months.', 250, 22),
    ('1 Year Membership','Access our boxing gym & workout facilities for 1 year.', 450, 22),
    ('Glove Rentals', 'Rent boxing gloves for the day.', 25, 23),
    ('Ring Rentals', 'Rent a boxing ring for 2 hrs.', 100, 23),
    ('Self Defense Class', 'Learn fighting skills for self defense.', 100, 24),
    ('Beginner Boxing Class', 'Learn the basics of boxing before you commit to a membership.', 75, 24),
    ('Season Training Plan', 'Detailed training plan formulated for your specific goals.', 300, 25),
    ('Seasonal Coach', 'Weekly practice session for 3 months with a coach.', 300, 25),
    ('Travel Team', 'Join our travel team for 3 months to train & compete.', 500, 26),
    ('Local Team', 'Join our local team for 3 months to train & compete.', 300, 26),
    ('2 hr Open Gym Session', 'Come train in our facilities for 2 hrs.', 100, 27),
    ('4 hr Open Gym Session', 'Come train in our facilities for 4 hrs.', 200, 27),
    ('Birthday Party', 'Host a 2 hr birthday party in our trampoline gym! Pizza included.', 250, 28),
    ('Trampoline Playdate', 'Come play in our trampoline gym for 2 hrs.', 50, 28), 
    ('Season Training Plan', 'Detailed training plan formulated for your specific goals.', 300, 29),
    ('Seasonal Coach', 'Weekly practice session for 3 months with a coach.', 300, 29),
    ('Speed & Agility Session', '2 hr workout session with a coach.', 150, 30),
    ('Skills Session', '2 hr workout session with a coach.', 150, 30),
    ('Lifting Session', '2 hr workout session with a coach.', 150, 30),
    ('Open Court Session', '2 hr session to access courts and practice individually.', 50, 30),
    ('Half Court Rental', 'Rent a half court for 2 hrs.', 250, 31),
    ('Full Court Rental', 'Rent a full court for 2 hrs.', 500, 31),
    ('Season Training Plan', 'Detailed training plan formulated for your specific goals.', 300, 33),
    ('Seasonal Coach', 'Weekly practice session for 3 months with a coach.', 300, 33),
    ('Speed & Agility Session', '2 hr workout session with a coach.', 150, 34),
    ('Skills Session', '2 hr workout session with a coach.', 150, 34),
    ('Lifting Session', '2 hr workout session with a coach.', 150, 34),
    ('Coaching Certification', 'Get certified to become a rugby coach in a 6 hr class.', 50, 35),
    ('Referee Certification', 'Get certified to become a rugby referee in a 6 hr class.', 50, 35);
    
    
    
    
    
    
    